# Generated by Django 4.1.4 on 2023-01-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angajati', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='angajati',
            name='link',
            field=models.CharField(default='STRING', max_length=100),
        ),
    ]
